# Site settings
author: Eric J Wilhite
title: 
header-img: img/home-bg.png
email: ericjwilhite@gmail.com
copyright_name: Eric J Wilhite
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: EricIsCoding
github_username:  EricIsCoding

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
